[features]
seeds = false
[programs.localnet]
tic_tac_toe = "Hne9PhgqGNZaDvJJP8jmMvoQoT4UJBFkim1ZLev1YhYL"
[programs.devnet]
tic_tac_toe = "Hne9PhgqGNZaDvJJP8jmMvoQoT4UJBFkim1ZLev1YhYL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/albererre/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
